import Head from "next/head";
import React from "react";
import { Josefin_Sans } from "@next/font/google";
import Header from "../components/Header";
import Link from "next/link";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import { useEffect } from "react";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300"],
  display: "swap",
});

export default function CommandeEffectuee() {
  const { asPath } = useRouter();
  let sessionId = asPath.split("session_id=")[1];

  const validationCommand = async () => {
    const session = {
      stripeCheckout: sessionId
    }
    const token = Cookies.get("token");
    const response = await fetch(
      process.env.NEXT_PUBLIC_API_HOST + "/validation-command",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(session),
      }
    );
    const result = await response.json();
  };

  useEffect(() => {
    validationCommand();
  }, []);

  return (
    <>
      <Head>
        <title>SIUMAIILOTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={josefinSans.className}>
        <Header />
          <div className="text-xl flex justify-center font-bold text-center my-20">
            <h1>Votre commande a bien été effectuée !<br/>
            SIU MAILLOT vous remercie de votre achat !</h1>
          </div>
          <Link href={"/"}>
            <button className="flex mx-auto bg-black text-white font-bold justify-center rounded-lg w-1/5">
              Retour à l'accueil
            </button>          
          </Link>      
        </main>
    </>
  );
}
