import Head from "next/head";
import { Josefin_Sans } from "@next/font/google";
import Header from "../components/Header";
import HubLogin from "../components/HubLogin";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300"],
  display: "swap",
});

export default function Connexion() {
  return (
    <>
      <Head>
        <title>SIUMAIILOTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={josefinSans.className}>
        <Header />
        <HubLogin />
      </main>
    </>
  );
}
