import Head from "next/head"
import React from "react";
import { Josefin_Sans } from '@next/font/google'
import Header from "../components/Header";
import { Card } from "../components/Card";

const josefinSans = Josefin_Sans({
    subsets: ['latin'],
    weight: ['300'],
    display: 'swap'
});

const elemPrefix = "Maillot";
const getId = (index: number) => `${elemPrefix}${index}`;
const getItems = () =>
  Array(20)
    .fill(0)
    .map((_, ind) => ({ id: getId(ind) }));

export default function EquipesNationales(){
    const [items] = React.useState(getItems);
    
    return (
        <>
        <Head>
            <title>SIUMAIILOTS</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={josefinSans.className}>
            <Header/>
            <div className="ml-2.5 my-5">
                <select className=" h-1/4	 border-solid border-2 border-black ml-20 rounded-lg" name="teams" id="teams">
                    <option value="">-- Vous pouvez filtrer par équipe nationale--</option>
                    <option value="france">France</option>
                    <option value="espagne">Espagne</option>
                    <option value="italie">Italie</option>
                    <option value="allemagne">Allemagne</option>
                    <option value="brésil">Brésil</option>
                    <option value="colombie">Colombie</option>
                    <option value="paraguay">Paraguay</option>
                    <option value="portugal">Portugal</option>
                    <option value="belgique">Belgique</option>
                    <option value="canada">Canada</option>
                    <option value="iran">Iran</option>
                    <option value="mexique">Mexique</option>
                    <option value="sénégal">Sénégal</option>
                    <option value="pologne">Pologne</option>
                    <option value="maroc">Maroc</option>
                </select>
            </div>

            <div className="grid grid-cols-5 gap-y-5 ml-20 justify-around text-center">
                {items.map(({ id }) => (
                    <Card
                        id={id}
                        title={id}
                        srcImage="/images/maillots/maillot.png"
                        price='30€'
                    />
                ))}
            </div>
        </main>
        </>
    )
}