import Header from "../components/Header";
import HeaderProfile from "../components/HeaderProfile";
import ElementsProfile from "../components/ElementsProfile";
import InfoProfile from "../components/InfoProfile";
import { Josefin_Sans } from "@next/font/google";
import Head from "next/head";
import { useRef, useState } from "react";
import { MouseEventHandler } from "react";
import Address from "../components/Address";
import Orders from "../components/Orders";
const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["300"],
});

export default function MyAccount() {
  const [subMenu, setSubMenu] = useState("informations");
  const [isInformationsSelected, setIsInformationsSelected] = useState(true);
  const [isAddressSelected, setIsAddressSelected] = useState(false);
  const [isOrdersSelected, setIsOrdersSelected] = useState(false);

  function displaySubMenu(subMenu: string) {
    setSubMenu(subMenu);
    switch (subMenu) {
      case "informations": {
        setIsInformationsSelected(true);
        setIsAddressSelected(false);
        setIsOrdersSelected(false);
        break;
      }
      case "address": {
        setIsInformationsSelected(false);
        setIsAddressSelected(true);
        setIsOrdersSelected(false);
        break;
      }
      case "orders": {
        setIsInformationsSelected(false);
        setIsAddressSelected(false);
        setIsOrdersSelected(true);
        break;
      }
    }

    return undefined;
  }
  //#9b9b9b
  return (
    <>
      <Head>
        <title>SIUMAIILOTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={josefinSans.className}>
        <Header />
        <div className="container mx-auto flex">
          <div className="w-3/12">
            <HeaderProfile />
            <div onClick={() => displaySubMenu("informations")}>
              <ElementsProfile
                name="Mes informations"
                selected={isInformationsSelected}
              />
            </div>
            <div onClick={() => displaySubMenu("address")}>
              <ElementsProfile
                name="Mes adresses"
                selected={isAddressSelected}
              />
            </div>
            <div onClick={() => displaySubMenu("orders")}>
              <ElementsProfile
                name="Mes commandes"
                selected={isOrdersSelected}
              />
            </div>
            <ElementsProfile name="Déconnexion" selected={false} />
          </div>
          <div className="w-9/12">
            {subMenu == "informations" && <InfoProfile />}
            {subMenu == "address" && <Address />}
            {subMenu == "orders" && <Orders />}
          </div>
        </div>
      </main>
    </>
  );
}
